'''

For building a Neural Vocoder (like HiFi-GAN) convert abstract acoustic features (like a Mel-spectogram) into hyper-realistic, 
natural-sounding human speech waveforms.
If MSE (Mean Squared Error) is used here then model will simply average all the possible wave variations, resulting in robotic, 
blurry, or muffled audio. But if Minimax / Adversarial Optimization is used by creating a high-stakes competition between two 
networks.

The Generator - It takes text or spectrogram inputs and synthesize raw audio waveforms. It wants to tricks human listeners and 
outsmart security systems.
The Dicriminator - It looks at the audio clips and spot the tiny, microscopic glitches like phase mistmatches, robotic metallic
hums, or unnatural vowel transitions that reveal the audio was generated by an AI.

Lets us consider this as a moving mountain situation, as hiker walking alone down the stationary hill. 
In Minimax optimization, the mountain is constantly moving. When the generator learns a new trick, like how to synthesize
realistic, crisp high-frequency sibilants (the '/s/' sound), it successfully takes a step down its error hill.   
However this action completely changes the landscape for the dicriminator . The generator old tricks doesnot works while 
spotting the fakes, which takes the discriminator back up the error hill. The discriminator now needs to recalculate the
gradients to look for deeper anomalies, like sub-harmonic distortions or phase issues.
Mathematically it is expressed as: min_G max_D V(D,G)
The optimizer is not trying to find a single low point on a static map. It is trying to navigate a fluid, continuous loop 
until both models reach a stalemate (Nash Equilibrium), where the generator is so brilliant that the discriminator is forced 
to guess completely at random (50/50) if the speech is real or artificial.

Lets create an authentic simulated voice signal (a 1-second vocal frequency wave) and compute its exact mathematical 
Mel-Spectrogram using raw tensors


'''


import torch
import torch.nn as nn
import torch.optim as optim

import matplotlib

torch.manual_seed(42)

#create a mathematically pure audio waveform frequency
sample_rate = 16000
duration = 1.0
t = torch.linspace(0, duration, int(sample_rate*duration))

#simulate vocal cord vibrations ( a fundamental frequency + harmonics)
fundamental_freq = 150.0 #typical human pitch

vocal_wave = torch.sin(2 * 3.14159 * fundamental_freq * t)
#add a high-frequency harmonic (to simulate the unique harmonic resonance of a spoken vowel sound)
vocal_wave += 0.5 * torch.sin(2 * 3.14159 * (fundamental_freq * 3) * t)

waveform = vocal_wave.unsqueeze(0) #shape : [1, 160000]

#extract acoustic features via mathematical matrix operations
#a mel-spectrogram cuts an audio signal into short window slices, performs Short-Time Fourier Transform (STFT), 
#and filters its.
window_size = 1024
hop_length = 512

window = torch.hann_window(window_size)
stft_matrix = torch.stft(waveform, n_fft=window_size, hop_length=hop_length,
                          win_length=window_size, window=window, return_complex=True)

magnitude_spectrogram = torch.abs(stft_matrix).squeeze(0)


mel_projection_weights = torch.randn(80, 513).abs()
real_voice_matrix = torch.matmul(mel_projection_weights, magnitude_spectrogram).t() #shape: [32, 80]

print(f"Audio Waveform generated! Time steps: {waveform.shape[1]} samples")
print(f"Processed Voice Feature Matrix Shape: {real_voice_matrix.shape} (32 time-steps, 80 Mel features)")


#setting the generator and dicriminator
class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(10, 64), nn.ReLU(), nn.Linear(64, 80))
    def forward(self, x):
        return self.net(x)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(80, 32), nn.ReLU(), nn.Linear(32, 1), nn.Sigmoid())
    def forward(self, x):
        return self.net(x)


generator = Generator()
discriminator = Discriminator()



#MiniMax optimization using the real voice profile

opt_G = optim.AdamW(generator.parameters(), lr=0.001)
opt_D = optim.AdamW(discriminator.parameters(), lr=0.001)
loss_fn = nn.BCELoss()

latent_noise = torch.randn(32, 10)

print("MiniMax Optimization on pure wave matrix")

for epoch in range(3):
    #phase A : optimize the discriminator
    opt_D.zero_grad()

    pred_real = discriminator(real_voice_matrix)
    loss_D_real = loss_fn(pred_real, torch.ones_like(pred_real))

    fake_voice_matrix = generator(latent_noise)
    pred_fake = discriminator(fake_voice_matrix.detach())
    loss_D_fake = loss_fn(pred_fake, torch.zeros_like(pred_fake))

    loss_D = (loss_D_real + loss_D_fake) / 2
    loss_D.backward()
    opt_D.step()

    #phase B : optimizer the cloning system that is the generator
    opt_G.zero_grad()

    pred_fake_updated = discriminator(fake_voice_matrix)
    loss_G = loss_fn(pred_fake_updated, torch.ones_like(pred_fake_updated))

    loss_G.backward()
    opt_G.step()
    print(f"Iteration {epoch+1}:")
    print(f"Dicriminator loss (D): {loss_D.item():.4f} [Tracking the audio waves anomalies]")
    print(f"Generator loss (G): {loss_G.item():.4f} [Learning real harmonic shapes]")